import assert from 'node:assert/strict';
import { createGrowthController, growthRequestKey } from './controller.mjs';
const contours = [{ area: 900, points: [{x:0,y:0},{x:30,y:0},{x:30,y:30},{x:0,y:30}] }];
let loads = 0;
const request = (sourceKey='font0:A', age=.08) => ({ sourceKey, settings: { age }, load: () => { loads++; return { contours }; } });
const controller = createGrowthController();
const finish = c => { let frames=0; while(c.state.pending && !c.state.error && !c.state.paused && !c.state.memoryPaused) { c.advance(12); assert.ok(++frames<10000); } };
controller.sync([request('font0:A',0)]); assert.equal(controller.state.total,0); assert.equal(loads,0);
controller.sync([request(),request(),request('font0:A',.12)]);
assert.equal(controller.state.total,1); assert.equal(loads,0,'Mask preparation is lazy');
assert.equal(controller.read('font0:A',{age:.12}),null,'Never return partial geometry');
controller.setPaused(true); controller.advance(); assert.equal(loads,0);
controller.setPaused(false); finish(controller); assert.equal(loads,1); assert.equal(controller.state.ready,1);
const bytes = controller.state.historyBytes;
assert.ok(controller.read('font0:A',{age:.12},.04));
assert.equal(controller.read('font0:A',{age:.12},.2),null,'Do not sample an unprepared future');
controller.sync([request('font0:A',.04)]); assert.equal(controller.state.pending,false);
assert.equal(controller.state.historyBytes,bytes,'Rewind reuses history');
const before = JSON.stringify(controller.read('font0:A',{age:.04}));
controller.read('font0:A',{age:.04}).rings[0].points[0].x = 9999;
assert.equal(JSON.stringify(controller.read('font0:A',{age:.04})),before,'Isolated playback output');
controller.sync([request('font1:A',.04)]); assert.equal(controller.read('font0:A',{age:.04}),null);
finish(controller); assert.equal(loads,2,'Loaded-font revision cannot reuse stale geometry');
assert.notEqual(growthRequestKey('a',{seed:1}),growthRequestKey('a',{seed:2}));
controller.sync([request('font2:A',.04),request('font2:B',.04)]);
controller.advance(0); assert.equal(loads,3,'Only one initialization in a task'); finish(controller);
assert.equal(controller.state.total,2); assert.equal(controller.state.ready,2);
controller.sync([]); assert.equal(controller.state.total,0); assert.equal(controller.state.paused,false);
controller.sync([{ ...request('bad'), load(){throw Error('mask failure');} }]);
controller.advance(); assert.equal(controller.state.error,'mask failure');
controller.sync([request('good',.01)]); assert.equal(controller.state.error,''); finish(controller);
controller.reset(); assert.equal(controller.state.historyBytes,0); assert.equal(controller.state.total,0);
controller.dispose(); assert.equal(controller.state.disposed,true); assert.throws(()=>controller.sync([]),/disposed/);
const constrained = createGrowthController({historyLimit:1});
constrained.sync([request('heavy',1)]); constrained.advance(0);
assert.equal(constrained.state.memoryPaused,true); assert.equal(constrained.state.total,1);
const memoryBefore = constrained.state.historyBytes; constrained.advance(12);
assert.equal(constrained.state.historyBytes,memoryBefore,'Memory backpressure does not continue work or drop a glyph');
constrained.allowMoreMemory(); assert.equal(constrained.state.memoryPaused,false); constrained.dispose();
console.log('Differential controller: lazy shared preparation, cancellation by replacement, pause/resume, rewind, font identity, isolated playback, error recovery and memory backpressure passed.');
