import assert from 'node:assert/strict';
import { createGrowthPool } from './pool.mjs';
const source=[{area:600,points:[{x:0,y:0},{x:30,y:0},{x:30,y:20},{x:0,y:20}]}];
const pool=createGrowthPool({idleEntries:1,idleHistoryBytes:1024*1024});
const a=pool.acquire('test-font-loaded:glyph-A',source,{age:.113}),b=pool.acquire('test-font-loaded:glyph-A',source,{age:.257});
assert.equal(pool.stats.entries,1,'Same source/settings share a trajectory across ages');
assert.equal(pool.stats.leases,2);assert.equal(a.sample(),null);
let turns=0;
while(b.state.status!=='ready'&&turns++<10000)pool.advance();
assert.ok(turns<10000);assert.equal(a.state.status,'ready');assert.equal(b.state.status,'ready');
const first=a.sample(),steps=pool.stats.completedSteps;
a.request(.257);assert.deepEqual(a.sample(),b.sample());
a.request(.113);assert.deepEqual(a.sample(),first);pool.advance();
assert.equal(pool.stats.completedSteps,steps,'Rewind and cached sample do not re-simulate');
const separate=createGrowthPool(),direct=separate.acquire('same-source',source,{age:.113});
while(direct.state.status!=='ready')separate.advance();
assert.deepEqual(direct.sample(),first,'Canonical checkpoints make access order independent');
const seed=pool.acquire('test-font-loaded:glyph-A',source,{age:0,seed:8});
const font=pool.acquire('different-font:glyph-A',source,{age:0});
assert.equal(pool.stats.activeEntries,3);assert.equal(seed.state.status,'ready');
a.release();assert.equal(pool.stats.leases,3);assert.equal(b.state.status,'ready');
b.release();seed.release();assert.equal(pool.stats.entries,2,'Trim idle LRU entries, preserve active glyph');
assert.equal(font.state.status,'ready');font.release();
assert.equal(pool.stats.entries,1);assert.ok(pool.stats.idleHistoryBytes<=1024*1024);
assert.throws(()=>a.request(.2),/released/);assert.throws(()=>a.sample(),/released/);
const active=pool.acquire('keep',source,{age:.2});pool.dispose();
assert.equal(pool.stats.entries,0);assert.equal(active.state.status,'released');assert.throws(()=>active.sample(),/released/);
assert.throws(()=>pool.acquire('after',source),/disposed/);
const noIdle=createGrowthPool({idleEntries:0,idleHistoryBytes:0});
const live1=noIdle.acquire('1',source,{age:0}),live2=noIdle.acquire('2',source,{age:0});
assert.equal(noIdle.stats.activeEntries,2,'Never drop active glyphs to hit an idle cache cap');
live1.release();live2.release();assert.equal(noIdle.stats.entries,0);
console.log('Differential pool: shared trajectory, canonical-age path independence, cached rewind, font/seed identity, active leases, idle LRU/history budget, stale handles and disposal passed. Active working-set memory is reported, not hard-capped.');
