import assert from 'node:assert/strict';
import {grow,resample} from './solver.mjs';
const circle=(radius,cx=0,cy=0,reverse=false)=>{let points=Array.from({length:48},(_,i)=>({x:cx+radius*Math.cos(i/48*2*Math.PI),y:cy+radius*Math.sin(i/48*2*Math.PI)}));if(reverse)points.reverse();let area=0;points.forEach((p,i)=>{const q=points[(i+1)%points.length];area+=p.x*q.y-q.x*p.y;});return {points,area:area*.5};};
const source=[circle(48),circle(19,0,0,true),circle(6,65,-40)];
const json=JSON.stringify(source), settings={age:.35,seed:19};
const a=grow(source,settings), b=grow(source,settings);
assert.equal(JSON.stringify(source),json,'Do not mutate the source');
assert.deepEqual(a,b,'Seeded simulation is repeatable');
assert.equal(a.rings.length,source.length,'Keep outer ring, hole, detached mark');
assert.ok(a.rings.every(r=>r.points.every(p=>Number.isFinite(p.x)&&Number.isFinite(p.y))));
assert.ok(a.maxPoints<=a.pointBudget,'Bound generated points without dropping contours');
assert.ok(a.rings[0].points.some((p,i)=>Math.hypot(p.x-resample(source[0].points,3.2)[i]?.x,p.y-resample(source[0].points,3.2)[i]?.y)>.1),'Growth must alter the body');
assert.notDeepEqual(a.rings,grow(source,{...settings,seed:23}).rings,'Seed changes nonuniform nutrient field');
assert.equal(grow(source,{age:0}).steps,0);
assert.equal(grow([],settings).rings.length,0);
assert.equal(grow(source,{age:-2,grain:Infinity,tension:NaN}).steps,0);
assert.throws(()=>grow([{area:1,points:[{x:NaN,y:0},{x:1,y:1},{x:2,y:0}]}]),TypeError);
assert.throws(()=>grow(null),TypeError);
console.log('Differential Type prototype: deterministic, finite, source immutable, ring identities retained, bounded settings, empty/invalid input pass. Not a self-intersection or runtime-UI proof.');
