/* Generated by scripts/build-sculpture.mjs. Source remains in .codex/prototypes. */
(function(root){
'use strict';
function createEngine(){
const modules = Object.create(null);
modules["anamorphic-type/core.mjs"] = (function () {
// Original two-profile intersection solid. Polygon rings use even-odd fill.
// A(x,y) AND B(-z/depth,y): two orthogonal readings of one material body.
// No voxel grid, copied sculpture, shadow optimizer, or editor registration.
const dot = (a,b) => a[0]*b[0]+a[1]*b[1]+a[2]*b[2];
const unit = a => { const d=Math.hypot(...a); return d ? a.map(x=>x/d) : [0,0,1]; };
const cross = (ax,ay,bx,by) => ax*by-ay*bx;
const clamp = (x,a,b) => Math.max(a,Math.min(b,x));
const option = (x,d,a,b) => Number.isFinite(x) ? clamp(x,a,b) : d;

const ANAMORPHIC_PRESETS = Object.freeze({
  dual: Object.freeze({yaw:45,tilt:0,depth:1,motion:0,metal:.25,roughness:.3}),
  oblique: Object.freeze({yaw:38,tilt:-24,depth:1.35,motion:0,metal:.7,roughness:.18}),
  reveal: Object.freeze({yaw:45,tilt:0,depth:1,motion:1,metal:.35,roughness:.3})
});
function anamorphicSettings(p={}) {
  return {yaw:option(p.yaw,45,-180,180),tilt:option(p.tilt,0,-80,80),depth:option(p.depth,1,.1,4),
    motion:option(p.motion,0,0,1),metal:option(p.metal,.3,0,1),roughness:option(p.roughness,.3,.04,1),
    opacity:option(p.opacity,1,0,1),unlit:!!p.unlit};
}
function box(edges) {
  let minX=Infinity,minY=Infinity,maxX=-Infinity,maxY=-Infinity;
  for(const e of edges){minX=Math.min(minX,e.minX);minY=Math.min(minY,e.minY);maxX=Math.max(maxX,e.maxX);maxY=Math.max(maxY,e.maxY);}
  return {minX,minY,maxX,maxY};
}
function tree(edges) {
  const bounds=box(edges);
  if(edges.length<=8)return {...bounds,edges};
  const axis=bounds.maxX-bounds.minX>=bounds.maxY-bounds.minY?'X':'Y';
  edges.sort((a,b)=>(a['min'+axis]+a['max'+axis])-(b['min'+axis]+b['max'+axis]));
  const half=edges.length>>1;
  return {...bounds,left:tree(edges.slice(0,half)),right:tree(edges.slice(half))};
}
// Internal shared normal field for valid, nondegenerate closed polygon rings.
// Exposing this helper does not change Anamorphic profile preparation.
function shadingTangents(points,radius){
  const cumulative=[0];
  for(let i=0;i<points.length;i++){const a=points[i],b=points[(i+1)%points.length];cumulative.push(cumulative[i]+Math.hypot(b.x-a.x,b.y-a.y));}
  const length=cumulative.at(-1);if(!length||!radius)return points.map(()=>null);
  const reach=Math.min(radius,length*.075);
  function at(s){
    s=((s%length)+length)%length;let lo=0,hi=points.length;
    while(lo+1<hi){const mid=(lo+hi)>>1;if(cumulative[mid]<=s)lo=mid;else hi=mid;}
    const a=points[lo],b=points[(lo+1)%points.length],span=cumulative[lo+1]-cumulative[lo],u=span?(s-cumulative[lo])/span:0;
    return {x:a.x+(b.x-a.x)*u,y:a.y+(b.y-a.y)*u};
  }
  return points.map((p,i)=>{
    const a=at(cumulative[i]-reach),b=at(cumulative[i]+reach),ix=p.x-a.x,iy=p.y-a.y,ox=b.x-p.x,oy=b.y-p.y;
    const cosine=(ix*ox+iy*oy)/Math.max(1e-30,Math.hypot(ix,iy)*Math.hypot(ox,oy));
    if(cosine<.6)return null; // retain genuine serif/corner creases
    const dx=b.x-a.x,dy=b.y-a.y,len=Math.hypot(dx,dy);
    return len?[dy/len,-dx/len]:null;
  });
}
function prepareAnamorphicProfile(input,{maxEdges=16384,smoothRadius=1.4}={}) {
  if(!Array.isArray(input)||!Number.isInteger(maxEdges)||maxEdges<3||!Number.isFinite(smoothRadius)||smoothRadius<0)throw new TypeError('Invalid profile or edge budget');
  const edges=[],rings=[];
  for(const ring of input){
    const points=(ring.points||ring).map(p=>{
      if(!p||!Number.isFinite(p.x)||!Number.isFinite(p.y))throw new TypeError('Non-finite profile point');
      return {x:p.x,y:p.y};
    });
    if(points.length<3)continue;
    rings.push(points);
    const shading=shadingTangents(points,smoothRadius);
    for(let i=0;i<points.length;i++){
      const a=points[i],b=points[(i+1)%points.length],dx=b.x-a.x,dy=b.y-a.y;
      if(!dx&&!dy)continue;
      if(edges.length>=maxEdges)throw new RangeError('Profile edge budget exceeded');
      const length=Math.hypot(dx,dy),normal=[dy/length,-dx/length];
      edges.push({x:a.x,y:a.y,dx,dy,n0:shading[i]||normal,n1:shading[(i+1)%points.length]||normal,
        minX:Math.min(a.x,b.x),maxX:Math.max(a.x,b.x),minY:Math.min(a.y,b.y),maxY:Math.max(a.y,b.y)});
    }
  }
  return {rings,edges,bounds:box(edges),tree:edges.length?tree(edges.slice()):null};
}
function lineBox(node,ox,oy,dx,dy) {
  let lo=-Infinity,hi=Infinity;
  for(const [o,d,min,max] of [[ox,dx,node.minX,node.maxX],[oy,dy,node.minY,node.maxY]]){
    if(Math.abs(d)<1e-14){if(o<min||o>max)return false;}
    else {const a=(min-o)/d,b=(max-o)/d;lo=Math.max(lo,Math.min(a,b));hi=Math.min(hi,Math.max(a,b));if(lo>hi)return false;}
  }
  return true;
}
function events(profile,ox,oy,dx,dy,stats) {
  const hits=[],side=dx<0||(dx===0&&dy<0)?-1:1;
  function visit(node){
    if(!lineBox(node,ox,oy,dx,dy))return;
    if(!node.edges){visit(node.left);visit(node.right);return;}
    for(const e of node.edges){
      if(stats && ++stats.edgeTests>stats.maxEdgeTests)throw new RangeError('Ray edge-test budget exceeded');
      // Canonical half-open side, independent of the ray's travel direction.
      // Reversing the ray must not swap top/bottom boundary inclusion. Tangent
      // extrema still contribute zero or two events, never one.
      const sa=cross(dx,dy,e.x-ox,e.y-oy),sb=cross(dx,dy,e.x+e.dx-ox,e.y+e.dy-oy);
      if((sa*side>0)===(sb*side>0))continue;
      const det=cross(dx,dy,e.dx,e.dy);
      const t=cross(e.x-ox,e.y-oy,e.dx,e.dy)/det;
      if(!Number.isFinite(t))continue;
      const u=clamp(sa/(sa-sb),0,1),n=[e.n0[0]*(1-u)+e.n1[0]*u,e.n0[1]*(1-u)+e.n1[1]*u];
      // Geometric intersections remain exact. Only lighting normals are
      // interpolated, on this ring alone; no cross-counter smoothing.
      const face=[e.dy,-e.dx],dotFace=face[0]*dx+face[1]*dy,dotShade=n[0]*dx+n[1]*dy;
      hits.push({t,n:dotFace*dotShade<0?face:n});
    }
  }
  if(profile.tree)visit(profile.tree);
  hits.sort((a,b)=>a.t-b.t);
  return hits;
}
function anamorphicContains(profile,x,y,stats=null) {
  if(!profile.tree||x<profile.bounds.minX||x>profile.bounds.maxX||y<profile.bounds.minY||y>profile.bounds.maxY)return false;
  let count=0;
  for(const hit of events(profile,x,y,1,0,stats))if(hit.t>0)count++;
  return count%2===1;
}
function intervals(profile,ox,oy,dx,dy,stats){
  if(!profile.tree)return [];
  if(Math.hypot(dx,dy)<1e-14)return anamorphicContains(profile,ox,oy,stats)?[{lo:-Infinity,hi:Infinity,n:null}]:[];
  const hit=events(profile,ox,oy,dx,dy,stats),result=[];
  // Each pair delimits an even-odd interior interval; zero-length tangencies
  // naturally disappear. No numerical distance stepping through thin ink.
  for(let i=0;i+1<hit.length;i+=2){
    if(hit[i+1].t<=hit[i].t)continue;
    let n=hit[i].n;if(n[0]*dx+n[1]*dy>0)n=[-n[0],-n[1]];
    result.push({lo:hit[i].t,hi:hit[i+1].t,n});
  }
  return result;
}
function anamorphicRay(a,b,origin,direction,depth=1,stats=null){
  if(!Number.isFinite(depth)||depth<=0||origin.length!==3||direction.length!==3
    ||!origin.every(Number.isFinite)||!direction.every(Number.isFinite)||!Math.hypot(...direction))throw new TypeError('Invalid ray');
  const ax=intervals(a,origin[0],origin[1],direction[0],direction[1],stats);
  if(!ax.length)return null;
  const bz=intervals(b,-origin[2]/depth,origin[1],-direction[2]/depth,direction[1],stats);
  let i=0,j=0;
  while(i<ax.length&&j<bz.length){
    const x=ax[i],z=bz[j],lo=Math.max(x.lo,z.lo),hi=Math.min(x.hi,z.hi);
    if(hi>Math.max(0,lo)){
      // Callers start outside the solid. Entry from inside is explicitly
      // reported without an invented entry normal.
      if(lo<0)return {t:0,normal:null,inside:true};
      const fromA=x.lo>=z.lo,n=fromA?x.n:z.n;
      const normal=fromA?[n[0],n[1],0]:[0,n[1],-n[0]/depth];
      return {t:lo,normal:unit(normal),inside:false};
    }
    if(x.hi<z.hi)i++;else j++;
  }
  return null;
}
function anamorphicView(settings={},phase=0){
  if(!Number.isFinite(phase))throw new TypeError('Invalid phase');
  const p=anamorphicSettings(settings),cycle=((phase%1)+1)%1;
  // A cosine shuttle returns to the identical solid/view at the loop seam.
  const degrees=p.yaw+45*p.motion*Math.cos(cycle*Math.PI*2),yaw=degrees*Math.PI/180,tilt=p.tilt*Math.PI/180;
  // Exact cardinal poses must not move boundary samples by cos(PI/2)'s tiny
  // residual. Do not snap nearby user poses or alter the continuous motion.
  const quadrant=degrees/90,cardinal=Number.isInteger(quadrant),q=((quadrant%4)+4)%4;
  const cy=cardinal?[1,0,-1,0][q]:Math.cos(yaw),sy=cardinal?[0,1,0,-1][q]:Math.sin(yaw),ct=Math.cos(tilt),st=Math.sin(tilt);
  return {right:[cy,0,-sy],down:[-sy*st,ct,-cy*st],toward:[sy*ct,st,cy*ct]};
}
function solidBox(a,b,depth){
  return {min:[a.bounds.minX,Math.max(a.bounds.minY,b.bounds.minY),-b.bounds.maxX*depth],
    max:[a.bounds.maxX,Math.min(a.bounds.maxY,b.bounds.maxY),-b.bounds.minX*depth]};
}
function rayBox(origin,direction,bounds){
  let lo=0,hi=Infinity;
  for(let i=0;i<3;i++){
    if(Math.abs(direction[i])<1e-14){if(origin[i]<bounds.min[i]||origin[i]>bounds.max[i])return false;}
    else {const a=(bounds.min[i]-origin[i])/direction[i],b=(bounds.max[i]-origin[i])/direction[i];
      lo=Math.max(lo,Math.min(a,b));hi=Math.min(hi,Math.max(a,b));if(lo>hi)return false;}
  }
  return hi>lo;
}
function renderAnamorphic(a,b,input={},frame={}){
  const {width=384,height=384,scale=1,centerX=0,centerY=0,samples=2,maxEdgeTests=100000000}=frame;
  if(!Number.isInteger(width)||!Number.isInteger(height)||width<1||height<1||width*height>4194304
    ||!Number.isInteger(samples)||samples<1||samples>4||![scale,centerX,centerY].every(Number.isFinite)||scale<=0
    ||!Number.isSafeInteger(maxEdgeTests)||maxEdgeTests<1)throw new RangeError('Invalid frame or work budget');
  const p=anamorphicSettings(input),view=anamorphicView(p,frame.phase??0),pixels=new Uint8ClampedArray(width*height*4);
  const stats={edgeTests:0,maxEdgeTests,rays:0,hits:0},bounds=solidBox(a,b,p.depth);
  if(!a.tree||!b.tree||bounds.min[1]>=bounds.max[1]||!p.opacity)return {pixels,width,height,stats};
  const ink=input.ink??[.21,.26,.25];
  if(!Array.isArray(ink)||ink.length!==3||!ink.every(v=>Number.isFinite(v)&&v>=0&&v<=1))throw new TypeError('Invalid ink RGB');
  const distance=Math.max(...bounds.min.map(Math.abs),...bounds.max.map(Math.abs))*3+1;
  const direction=view.toward.map(v=>-v),key=unit([-.55,-.75,1]),rim=unit([.9,.25,.5]),half=unit([key[0],key[1],key[2]+1]);
  for(let y=0;y<height;y++)for(let x=0;x<width;x++){
    let count=0,red=0,green=0,blue=0;
    for(let sy=0;sy<samples;sy++)for(let sx=0;sx<samples;sx++){
      const px=(x+(sx+.5)/samples-width/2)/scale+centerX,py=(y+(sy+.5)/samples-height/2)/scale+centerY;
      const origin=view.right.map((v,i)=>v*px+view.down[i]*py+view.toward[i]*distance);
      if(!rayBox(origin,direction,bounds))continue;
      stats.rays++;
      const hit=anamorphicRay(a,b,origin,direction,p.depth,stats);if(!hit)continue;
      stats.hits++;count++;
      if(p.unlit){red+=ink[0];green+=ink[1];blue+=ink[2];continue;}
      const n=hit.normal,nv=[dot(n,view.right),dot(n,view.down),dot(n,view.toward)];
      const diffuse=.22+.6*Math.max(0,dot(nv,key))+.17*Math.max(0,dot(nv,rim));
      const exponent=2+126*(1-p.roughness)**2,specular=Math.max(0,dot(nv,half))**exponent;
      const edge=(1-Math.max(0,nv[2]))**4;
      const sheen=specular*(.2+p.metal*.75)+edge*p.metal*.2;
      red+=clamp(ink[0]*diffuse+sheen,0,1);green+=clamp(ink[1]*diffuse+sheen,0,1);blue+=clamp(ink[2]*diffuse+sheen,0,1);
    }
    if(count){const k=(y*width+x)*4;pixels[k]=red/count*255;pixels[k+1]=green/count*255;pixels[k+2]=blue/count*255;
      pixels[k+3]=count/(samples*samples)*p.opacity*255;}
  }
  return {pixels,width,height,stats};
}
// Integrate horizontal support exactly over all vertex-height slabs. This
// diagnoses incompatible readings; it never fills, warps or deletes the input.
function anamorphicCompatibility(a,b,{maxEdgeTests=100000000}={}){
  if(!Number.isSafeInteger(maxEdgeTests)||maxEdgeTests<1)throw new RangeError('Invalid compatibility budget');
  const stats={edgeTests:0,maxEdgeTests};
  const ys=[...new Set([...a.rings,...b.rings].flatMap(r=>r.map(p=>p.y)))].sort((x,y)=>x-y);
  let areaA=0,areaB=0,retainedA=0,retainedB=0;
  for(let i=0;i+1<ys.length;i++){
    const dy=ys[i+1]-ys[i],y=(ys[i]+ys[i+1])/2;
    const ia=intervals(a,0,y,1,0,stats),ib=intervals(b,0,y,1,0,stats);
    const wa=ia.reduce((s,q)=>s+q.hi-q.lo,0),wb=ib.reduce((s,q)=>s+q.hi-q.lo,0);
    areaA+=wa*dy;areaB+=wb*dy;if(wb>0)retainedA+=wa*dy;if(wa>0)retainedB+=wb*dy;
  }
  return {areaA,areaB,retainedA,retainedB,lossA:areaA?1-retainedA/areaA:0,lossB:areaB?1-retainedB/areaB:0,edgeTests:stats.edgeTests};
}

return {ANAMORPHIC_PRESETS,anamorphicSettings,shadingTangents,prepareAnamorphicProfile,anamorphicContains,anamorphicRay,anamorphicView,renderAnamorphic,anamorphicCompatibility};
})();
modules["anamorphic-type/studio.mjs"] = (function () {
// Original, analytic camera-rig studio. No environment image, texture lookup,
// copied BRDF, ray-traced shadow or physical light-transport claim.
const unit=a=>{const n=Math.hypot(...a);return a.map(v=>v/n);};
const dot=(a,b)=>a[0]*b[0]+a[1]*b[1]+a[2]*b[2];
const cross=(a,b)=>[a[1]*b[2]-a[2]*b[1],a[2]*b[0]-a[0]*b[2],a[0]*b[1]-a[1]*b[0]];
const smooth=x=>{x=Math.max(0,Math.min(1,x));return x*x*(3-2*x);};
const panels=[
  {direction:[-.42,-.48,.77],width:.65,height:.9,power:3.5},
  {direction:[.8,.15,.58],width:.24,height:.8,power:2.4},
  {direction:[-.7,.4,-.6],width:.36,height:.75,power:2.6}
].map(p=>{const d=unit(p.direction),u=unit(cross([0,1,0],d));return {...p,d,u,v:cross(d,u)};});

// Roughness broadens the analytic panel lobes and reduces their peak. This is
// a bounded, continuous approximation, NOT a GGX environment convolution.
function prepareStudio(roughness){
  if(!Number.isFinite(roughness)||roughness<.04||roughness>1)throw new RangeError('Invalid studio roughness');
  const blur=.015+.6*roughness*roughness;
  const lights=panels.map(p=>{const w=Math.hypot(p.width,blur),h=Math.hypot(p.height,blur);return {...p,w,h,power:p.power*p.width*p.height/(w*h)};});
  return (nx,ny,nz)=>{
    // Orthographic outgoing direction (0,0,1). Reflection is in view space,
    // so pan/zoom have no lighting input and normals drive every reflection.
    const r=[2*nx*nz,2*ny*nz,2*nz*nz-1];
    let energy=.07+.16*smooth((1-r[1])*.5);
    for(const p of lights){const a=dot(r,p.u)/p.w,b=dot(r,p.v)/p.h;
      energy+=p.power*Math.exp(-a*a-b*b)*smooth(dot(r,p.d)/.4);
    }
    return energy;
  };
}

// Input ink is a display RGB reflectance tint. Convert only this optional
// finish to a linear approximation; the existing classic path stays exact.
function studioChannel(tint,nz,energy){
  const f0=tint**2.2,f=f0+(1-f0)*(1-Math.max(0,Math.min(1,nz)))**5;
  const light=f*energy;
  return (light/(1+light))**(1/2.2);
}

return {prepareStudio,studioChannel};
})();
modules["anamorphic-type/surface.mjs"] = (function () {
// Cached boundary of A(x,y) AND B(-z,y). Depth is a later affine transform.
// Polygon-height slabs, not a voxel resolution: no source vertices discarded.
// Display triangle soup, not a welded/manufacturing mesh. core.mjs is the oracle.
const {anamorphicSettings,anamorphicView} = modules["anamorphic-type/core.mjs"];
const {prepareStudio,studioChannel} = modules["anamorphic-type/studio.mjs"];
const dot=(a,b)=>a[0]*b[0]+a[1]*b[1]+a[2]*b[2];
const cross=(a,b)=>[a[1]*b[2]-a[2]*b[1],a[2]*b[0]-a[0]*b[2],a[0]*b[1]-a[1]*b[0]];
const sub=(a,b)=>a.map((v,i)=>v-b[i]);
const unit=a=>{const d=Math.hypot(...a);return a.map(v=>v/d);};
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
function atY(e,y){
  // Shared source vertices are reproduced exactly at slab joins.
  if(y===e.y)return e.x;
  if(y===(e.dy>0?e.maxY:e.minY))return e.dx>0?e.maxX:e.minX;
  return e.x+e.dx*((y-e.y)/e.dy);
}
function edgeNormal(e,x,y,axis,sign){
  const t=clamp(Math.abs(e.dx)>Math.abs(e.dy)?(x-e.x)/e.dx:(y-e.y)/e.dy,0,1);
  const nx=(e.n0[0]*(1-t)+e.n1[0]*t)*sign,ny=(e.n0[1]*(1-t)+e.n1[1]*t)*sign;
  return axis===0?[nx,ny,0]:[0,ny,-nx];
}
function sweep(profile,tick){
  const edges=profile.edges.filter(e=>e.dy).sort((a,b)=>a.minY-b.minY),active=new Set();let cursor=0;
  return (y0,y1)=>{
    // Test the slab endpoints, not a rounded midpoint that can equal a vertex
    // when two consecutive source heights are adjacent floating-point values.
    while(cursor<edges.length&&edges[cursor].minY<=y0)active.add(edges[cursor++]);
    const hits=[];
    for(const e of active){tick();if(e.maxY<y1){active.delete(e);continue;}hits.push({e,x:atY(e,y0)/2+atY(e,y1)/2});}
    hits.sort((a,b)=>a.x-b.x);
    if(hits.length%2)throw new Error('Odd profile crossing count');
    const pairs=[];for(let i=0;i+1<hits.length;i+=2)if(atY(hits[i+1].e,y0)>atY(hits[i].e,y0)||atY(hits[i+1].e,y1)>atY(hits[i].e,y1))pairs.push([hits[i].e,hits[i+1].e]);
    return pairs;
  };
}
const intervalsAt=(pairs,y)=>pairs.map(p=>p.map(e=>atY(e,y))).filter(p=>p[1]>p[0]);
const member=(intervals,x)=>intervals.some(p=>p[0]<x&&x<p[1]);
function buildAnamorphicSurface(a,b,{maxTriangles=200000,maxWork=20000000,indexed=false}={}){
  if(!Number.isSafeInteger(maxTriangles)||maxTriangles<1||!Number.isSafeInteger(maxWork)||maxWork<1)throw new RangeError('Invalid surface budget');
  const positions=[],normals=[],faceNormals=[],sourceAxis=[];
  const indices=[],vertices=indexed?new Map():null;
  const stats={triangles:0,slabs:0,caps:0,work:0};
  const tick=()=>{if(++stats.work>maxWork)throw new RangeError('Surface work budget exceeded');};
  function triangle(p,n,face,axis){
    const area=cross(sub(p[1],p[0]),sub(p[2],p[0]));
    if(!area.some(v=>v))return;
    if(![...p.flat(),...n.flat(),...area].every(Number.isFinite))throw new RangeError('Non-finite surface geometry');
    if(stats.triangles>=maxTriangles)throw new RangeError('Surface triangle budget exceeded');
    if(dot(area,face)<0){[p[1],p[2]]=[p[2],p[1]];[n[1],n[2]]=[n[2],n[1]];}
    if(indexed){
      for(let i=0;i<3;i++){
        const component=v=>Object.is(v,-0)?'-0':String(v);
        const key=p[i].map(component).join(',')+':'+n[i].map(component).join(',');let id=vertices.get(key);
        if(id===undefined){id=positions.length/3;vertices.set(key,id);positions.push(...p[i]);normals.push(...n[i]);}
        indices.push(id);
      }
    }else{positions.push(...p.flat());normals.push(...n.flat());}
    faceNormals.push(...unit(face));sourceAxis.push(axis);stats.triangles++;
  }
  function quad(p,n,face,axis){triangle([p[0],p[1],p[2]],[n[0],n[1],n[2]],face,axis);triangle([p[0],p[2],p[3]],[n[0],n[2],n[3]],face,axis);}
  function side(e,span,y0,y1,axis,polarity){
    const sign=polarity*Math.sign(e.dy),face=axis===0?[e.dy*sign,-e.dx*sign,0]:[0,-e.dx*sign,-e.dy*sign];
    const points=[[y0,span[0]],[y0,span[1]],[y1,span[1]],[y1,span[0]]].map(([y,q])=>{
      const x=atY(e,y),u=atY(q,y);return axis===0?[x,y,-u]:[u,y,-x];
    });
    const ns=points.map(p=>edgeNormal(e,axis===0?p[0]:-p[2],p[1],axis,sign));quad(points,ns,face,axis);
  }
  const horizontals=p=>{const result=new Map();for(const e of p.edges)if(!e.dy){const list=result.get(e.y)||[];list.push(e);result.set(e.y,list);}return result;};
  const ha=horizontals(a),hb=horizontals(b);
  function cap(before,after,y){
    const lowA=intervalsAt(before.a,y),lowB=intervalsAt(before.b,y),highA=intervalsAt(after.a,y),highB=intervalsAt(after.b,y);
    const xs=[...new Set([...lowA.flat(),...highA.flat(),...(ha.get(y)||[]).flatMap(e=>[e.minX,e.maxX])])].sort((x,y)=>x-y);
    const us=[...new Set([...lowB.flat(),...highB.flat(),...(hb.get(y)||[]).flatMap(e=>[e.minX,e.maxX])])].sort((x,y)=>x-y);
    for(let i=0;i+1<xs.length;i++){
      const x=(xs[i]+xs[i+1])/2,la=member(lowA,x),ua=member(highA,x);if(!la&&!ua)continue;
      for(let j=0;j+1<us.length;j++){
        tick();const u=(us[j]+us[j+1])/2,lb=member(lowB,u),ub=member(highB,u),low=la&&lb,high=ua&&ub;
        if(low===high)continue;
        const axis=la!==ua?0:2,coordinate=axis===0?x:u;
        const e=(axis===0?ha:hb).get(y)?.find(e=>e.minX<=coordinate&&coordinate<=e.maxX);
        if(!e)throw new Error('Missing horizontal boundary; simple closed rings required');
        const polarity=low?1:-1,sign=-polarity*Math.sign(e.dx),face=[0,polarity,0];
        const p=[[xs[i],y,-us[j]],[xs[i+1],y,-us[j]],[xs[i+1],y,-us[j+1]],[xs[i],y,-us[j+1]]];
        const n=p.map(q=>edgeNormal(e,axis===0?q[0]:-q[2],y,axis,sign));quad(p,n,face,axis);stats.caps++;
      }
    }
  }
  const ys=[...new Set([...a.rings,...b.rings].flatMap(r=>r.map(p=>p.y)))].sort((x,y)=>x-y);
  const scanA=sweep(a,tick),scanB=sweep(b,tick);let before={a:[],b:[]};
  for(let i=0;i+1<ys.length;i++){
    tick();const y0=ys[i],y1=ys[i+1];
    const after={a:scanA(y0,y1),b:scanB(y0,y1)};cap(before,after,y0);
    for(const ap of after.a)for(const bp of after.b){
      tick();side(ap[0],bp,y0,y1,0,-1);side(ap[1],bp,y0,y1,0,1);
      side(bp[0],ap,y0,y1,2,-1);side(bp[1],ap,y0,y1,2,1);
    }
    stats.slabs++;before=after;
  }
  if(ys.length)cap(before,{a:[],b:[]},ys.at(-1));
  const bounds={min:[a.bounds.minX,Math.max(a.bounds.minY,b.bounds.minY),-b.bounds.maxX],max:[a.bounds.maxX,Math.min(a.bounds.maxY,b.bounds.maxY),-b.bounds.minX]};
  return {positions:Float64Array.from(positions),normals:Float64Array.from(normals),faceNormals:Float64Array.from(faceNormals),sourceAxis:Uint8Array.from(sourceAxis),...(indexed?{indices:Uint32Array.from(indices)}:{}),triangleCount:stats.triangles,bounds,stats};
}

// CPU triangle display path; source intersection and normal construction are
// not re-evaluated per pixel. This is NOT a browser/GPU implementation.
function renderAnamorphicSurface(mesh,input={},frame={}){
  const {width=384,height=384,scale=1,centerX=0,centerY=0,samples=2,maxSampleTests=100000000,maxSamples=4194304}=frame;
  if(!Number.isInteger(width)||!Number.isInteger(height)||width<1||height<1||width*height>4194304
    ||!Number.isInteger(samples)||samples<1||samples>4||![scale,centerX,centerY].every(Number.isFinite)||scale<=0
    ||!Number.isSafeInteger(maxSampleTests)||maxSampleTests<1||!Number.isSafeInteger(maxSamples)||maxSamples<1||width*height*samples*samples>maxSamples)throw new RangeError('Invalid surface frame or work budget');
  const finish=input.finish??'classic';
  if(finish!=='classic'&&finish!=='studio')throw new TypeError('Invalid surface finish');
  const p=anamorphicSettings(input),view=anamorphicView(p,frame.phase??0),pixels=new Uint8ClampedArray(width*height*4);
  const studio=finish==='studio'&&p.metal&&!p.unlit?prepareStudio(p.roughness):null;
  const stats={triangles:mesh.triangleCount,visibleTriangles:0,rowTests:0,sampleTests:0,hits:0,maxSampleTests};
  if(!mesh.triangleCount||!p.opacity)return {pixels,width,height,stats};
  const indices=mesh.indices;
  if(indices!==undefined&&(!(indices instanceof Uint32Array)||indices.length!==mesh.triangleCount*3||mesh.positions.length%3||mesh.normals.length!==mesh.positions.length||mesh.faceNormals.length!==mesh.triangleCount*3||mesh.sourceAxis.length!==mesh.triangleCount||!indices.every(i=>i<mesh.positions.length/3)))throw new TypeError('Invalid indexed surface');
  const ink=input.ink??[.21,.26,.25];if(!Array.isArray(ink)||ink.length!==3||!ink.every(v=>Number.isFinite(v)&&v>=0&&v<=1))throw new TypeError('Invalid ink RGB');
  // Optional exact face-material palette for other glyph solids (e.g. a
  // duplex Scroll sheet). Anamorphic's default single material is unchanged.
  const palette=input.axisInks;
  if(palette!==undefined&&(!Array.isArray(palette)||palette.length!==3||!palette.every(c=>Array.isArray(c)&&c.length===3&&c.every(v=>Number.isFinite(v)&&v>=0&&v<=1))||!mesh.sourceAxis.every(a=>a<3)))throw new TypeError('Invalid surface material palette');
  const sw=width*samples,sh=height*samples,count=sw*sh,zbuffer=new Float64Array(count).fill(-Infinity),owners=new Int32Array(count).fill(-1);
  const baryA=new Float64Array(count),baryB=new Float64Array(count);
  const screen=new Float64Array(mesh.positions.length),faces=new Float64Array(mesh.faceNormals.length),shade=new Float64Array(mesh.normals.length);
  for(let i=0;i<mesh.positions.length;i+=3){
    const point=[mesh.positions[i],mesh.positions[i+1],mesh.positions[i+2]*p.depth];
    screen[i]=((dot(point,view.right)-centerX)*scale+width/2)*samples;
    screen[i+1]=((dot(point,view.down)-centerY)*scale+height/2)*samples;screen[i+2]=dot(point,view.toward);
    if(!Number.isFinite(screen[i])||!Number.isFinite(screen[i+1])||!Number.isFinite(screen[i+2]))throw new RangeError('Non-finite projected surface');
    const n=[mesh.normals[i],mesh.normals[i+1],mesh.normals[i+2]/p.depth];
    shade[i]=dot(n,view.right);shade[i+1]=dot(n,view.down);shade[i+2]=dot(n,view.toward);
  }
  for(let i=0;i<mesh.faceNormals.length;i+=3){
    const n=unit([mesh.faceNormals[i],mesh.faceNormals[i+1],mesh.faceNormals[i+2]/p.depth]);
    faces[i]=dot(n,view.right);faces[i+1]=dot(n,view.down);faces[i+2]=dot(n,view.toward);
  }
  const edge=(ax,ay,bx,by,x,y)=>(bx-ax)*(y-ay)-(by-ay)*(x-ax);
  const topLeft=(ax,ay,bx,by)=>by<ay||(by===ay&&bx>ax);
  for(let tri=0;tri<mesh.triangleCount;tri++){
    if(faces[tri*3+2]<=1e-14)continue;
    const k=indices?indices[tri*3]*3:tri*9,kb=indices?indices[tri*3+1]*3:k+3,kc=indices?indices[tri*3+2]*3:k+6;
    const ax=screen[k],ay=screen[k+1],bx=screen[kb],by=screen[kb+1],cx=screen[kc],cy=screen[kc+1];
    const area=edge(ax,ay,bx,by,cx,cy);if(!area)continue;const sign=Math.sign(area),abs=Math.abs(area);
    const xmin=Math.max(0,Math.ceil(Math.min(ax,bx,cx)-.5)),xmax=Math.min(sw-1,Math.floor(Math.max(ax,bx,cx)-.5));
    const ymin=Math.max(0,Math.ceil(Math.min(ay,by,cy)-.5)),ymax=Math.min(sh-1,Math.floor(Math.max(ay,by,cy)-.5));
    if(xmin>xmax||ymin>ymax)continue;stats.visibleTriangles++;
    const ab=sign>0?topLeft(ax,ay,bx,by):topLeft(bx,by,ax,ay),bc=sign>0?topLeft(bx,by,cx,cy):topLeft(cx,cy,bx,by),ca=sign>0?topLeft(cx,cy,ax,ay):topLeft(ax,ay,cx,cy);
    for(let y=ymin;y<=ymax;y++){
      if(++stats.rowTests>maxSampleTests)throw new RangeError('Surface row-test budget exceeded');
      // Long tilted strips have huge bounding boxes but tiny row spans. Clip
      // the candidate interval before the exact edge test, not after sampling
      // the entire box. Expand out by one sample to retain roundoff boundaries.
      const py=y+.5;let left=Infinity,right=-Infinity;
      function cut(x0,y0,x1,y1){
        if(py<Math.min(y0,y1)||py>Math.max(y0,y1))return;
        if(y0===y1){left=Math.min(left,x0,x1);right=Math.max(right,x0,x1);return;}
        const x=x0+(x1-x0)*(py-y0)/(y1-y0);left=Math.min(left,x);right=Math.max(right,x);
      }
      cut(ax,ay,bx,by);cut(bx,by,cx,cy);cut(cx,cy,ax,ay);
      const from=Math.max(xmin,Math.floor(left-.5)),to=Math.min(xmax,Math.ceil(right-.5));
      for(let x=from;x<=to;x++){
      if(++stats.sampleTests>maxSampleTests)throw new RangeError('Surface sample-test budget exceeded');
      const ea=edge(bx,by,cx,cy,x+.5,y+.5)*sign,eb=edge(cx,cy,ax,ay,x+.5,y+.5)*sign,ec=edge(ax,ay,bx,by,x+.5,y+.5)*sign;
      if(ea<0||eb<0||ec<0||(!ea&&!bc)||(!eb&&!ca)||(!ec&&!ab))continue;
      const wa=ea/abs,wb=eb/abs,wc=1-wa-wb,z=wa*screen[k+2]+wb*screen[kb+2]+wc*screen[kc+2],q=y*sw+x;
      if(z<zbuffer[q])continue;
      // A owns coincident profile entries, as in the independent ray oracle.
      if(z===zbuffer[q]&&owners[q]>=0&&mesh.sourceAxis[owners[q]]<=mesh.sourceAxis[tri])continue;
      zbuffer[q]=z;owners[q]=tri;baryA[q]=wa;baryB[q]=wb;
      }
    }
  }
  const key=unit([-.55,-.75,1]),rim=unit([.9,.25,.5]),half=unit([key[0],key[1],key[2]+1]),exponent=2+126*(1-p.roughness)**2;
  for(let y=0;y<height;y++)for(let x=0;x<width;x++){
    let hits=0,r=0,g=0,b=0;
    for(let sy=0;sy<samples;sy++)for(let sx=0;sx<samples;sx++){
      const q=(y*samples+sy)*sw+x*samples+sx,tri=owners[q];if(tri<0)continue;hits++;
      const material=palette?palette[mesh.sourceAxis[tri]]:ink;
      if(p.unlit){r+=material[0];g+=material[1];b+=material[2];continue;}
      const k=indices?indices[tri*3]*3:tri*9,kb=indices?indices[tri*3+1]*3:k+3,kc=indices?indices[tri*3+2]*3:k+6,wa=baryA[q],wb=baryB[q],wc=1-wa-wb;
      let nx=shade[k]*wa+shade[kb]*wb+shade[kc]*wc,ny=shade[k+1]*wa+shade[kb+1]*wb+shade[kc+1]*wc,nz=shade[k+2]*wa+shade[kb+2]*wb+shade[kc+2]*wc;
      if(nz<0){nx=faces[tri*3];ny=faces[tri*3+1];nz=faces[tri*3+2];}
      const length=Math.hypot(nx,ny,nz);nx/=length;ny/=length;nz/=length;
      const diffuse=.22+.6*Math.max(0,nx*key[0]+ny*key[1]+nz*key[2])+.17*Math.max(0,nx*rim[0]+ny*rim[1]+nz*rim[2]);
      const specular=Math.max(0,nx*half[0]+ny*half[1]+nz*half[2])**exponent,sheen=specular*(.2+p.metal*.75)+(1-Math.max(0,nz))**4*p.metal*.2;
      const cr=clamp(material[0]*diffuse+sheen,0,1),cg=clamp(material[1]*diffuse+sheen,0,1),cb=clamp(material[2]*diffuse+sheen,0,1);
      if(studio){const energy=studio(nx,ny,nz),m=p.metal;
        r+=cr*(1-m)+studioChannel(material[0],nz,energy)*m;
        g+=cg*(1-m)+studioChannel(material[1],nz,energy)*m;
        b+=cb*(1-m)+studioChannel(material[2],nz,energy)*m;
      }else{r+=cr;g+=cg;b+=cb;}
    }
    if(hits){const k=(y*width+x)*4;pixels[k]=r/hits*255;pixels[k+1]=g/hits*255;pixels[k+2]=b/hits*255;pixels[k+3]=hits/(samples*samples)*p.opacity*255;stats.hits+=hits;}
  }
  return {pixels,width,height,stats};
}

return {buildAnamorphicSurface,renderAnamorphicSurface};
})();
modules["scroll-type/core.mjs"] = (function () {
// A cut glyph sheet bent along an arc-length directrix. No font template,
// glyph overlay, physical cloth solve, browser registration or shadow study.
const {renderAnamorphicSurface} = modules["anamorphic-type/surface.mjs"];
const {shadingTangents} = modules["anamorphic-type/core.mjs"];
const TAU=2*Math.PI, clamp=(x,a,b)=>Math.max(a,Math.min(b,x));
const opt=(v,d,a,b)=>Number.isFinite(v)?clamp(v,a,b):d;
const cross=(a,b)=>[a[1]*b[2]-a[2]*b[1],a[2]*b[0]-a[0]*b[2],a[0]*b[1]-a[1]*b[0]];
const sub=(a,b)=>a.map((v,i)=>v-b[i]);
const dot=(a,b)=>a.reduce((r,v,i)=>r+v*b[i],0);
const unit=a=>{const n=Math.hypot(...a);return n?a.map(v=>v/n):[0,0,1];};
const SCROLL_PRESETS=Object.freeze({
  volute:Object.freeze({mode:'spiral',curl:1.15,taper:.85,gauge:.012,yaw:-28,tilt:-22,motion:0,metal:.65,roughness:.2}),
  scroll:Object.freeze({mode:'roll',curl:.62,taper:0,gauge:.008,yaw:28,tilt:18,motion:0,metal:.25,roughness:.3}),
  reverse:Object.freeze({mode:'reverse',curl:1.25,taper:0,gauge:.01,yaw:-30,tilt:-15,motion:0,metal:.55,roughness:.24})
});
function scrollSettings(p={}){
  return {mode:['roll','spiral','reverse'].includes(p.mode)?p.mode:'spiral',curl:opt(p.curl,1.15,-3,3),
    taper:opt(p.taper,.85,-.95,.95),gauge:opt(p.gauge,.012,0,.03),
    yaw:opt(p.yaw,-28,-180,180),tilt:opt(p.tilt,-22,-80,80),motion:opt(p.motion,0,0,1),
    metal:opt(p.metal,.65,0,1),roughness:opt(p.roughness,.2,.04,1),opacity:opt(p.opacity,1,0,1),unlit:!!p.unlit};
}
function angle(v,span,p,phase){
  const time=((phase%1)+1)%1,drive=1-p.motion*.4*(1-Math.cos(TAU*time));
  const k=TAU*p.curl*drive,s=v/span;
  if(p.mode==='reverse')return {theta:2*k*s*s,curvature:4*k*s/span};
  if(p.mode==='spiral')return {theta:k*(s+p.taper*s*s),curvature:k*(1+2*p.taper*s)/span};
  return {theta:k*s,curvature:k/span};
}
// Eight-point Gauss-Legendre, split by a conservative angular-variation bound.
// This integrates unit tangents, not linearly interpolated sampled positions.
const GX=[.1834346424956498,.525532409916329,.7966664774136267,.9602898564975363];
const GW=[.362683783378362,.3137066458778873,.2223810344533745,.1012285362903763];
function scrollSection(v,span,input={},phase=0){
  if(!Number.isFinite(v)||!Number.isFinite(span)||span<=0||Math.abs(v)>span*.500000000001||!Number.isFinite(phase))throw new RangeError('Invalid scroll section');
  const p=scrollSettings(input),state=angle(v,span,p,phase);
  if(!p.curl)return {y:v,z:0,theta:0,curvature:0};
  const divisions=Math.max(1,Math.ceil(Math.abs(v)*12*Math.PI/span/.35));
  let y=0,z=0;
  for(let j=0;j<divisions;j++){
    const a=v*j/divisions,b=v*(j+1)/divisions,m=(a+b)/2,h=(b-a)/2;
    for(let i=0;i<4;i++)for(const sign of [-1,1]){const t=angle(m+sign*h*GX[i],span,p,phase).theta;y+=h*GW[i]*Math.cos(t);z+=h*GW[i]*Math.sin(t);}
  }
  return {y,z,...state};
}
function contains(r,x,y){let yes=false;for(let i=0;i<r.length;i++){const a=r[i],b=r[(i+1)%r.length];if((a.v>y)!==(b.v>y)&&x<(b.u-a.u)*(y-a.v)/(b.v-a.v)+a.u)yes=!yes;}return yes;}
function area(r){const o=r[0];let sum=0;for(let i=0;i<r.length;i++){const a=r[i],b=r[(i+1)%r.length];sum+=(a.u-o.u)*(b.v-o.v)-(b.u-o.u)*(a.v-o.v);}return sum/2;}
function edgeAt(e,v){if(v===e.a.v)return e.a.u;if(v===e.b.v)return e.b.u;return e.a.u+(e.b.u-e.a.u)*(v-e.a.v)/(e.b.v-e.a.v);}
function prepareScrollSource(input,{axis=0,steps=480,rimSmoothing=.007,maxPoints=100000,maxTriangles=200000,maxWork=5000000}={}){
  if(!Array.isArray(input)||!Number.isFinite(axis)||!Number.isInteger(steps)||steps<8||steps>4096
    ||!Number.isFinite(rimSmoothing)||rimSmoothing<0||rimSmoothing>.03
    ||![maxPoints,maxTriangles,maxWork].every(n=>Number.isSafeInteger(n)&&n>0))throw new RangeError('Invalid scroll source options');
  const a=axis*Math.PI/180,ux=Math.cos(a),uy=Math.sin(a),rings=[];
  let minV=Infinity,maxV=-Infinity,inputPoints=0;
  for(const ring of input){const r=[];for(const q of (ring.points||ring)){
    if(!q||!Number.isFinite(q.x)||!Number.isFinite(q.y))throw new TypeError('Invalid source point');
    if(++inputPoints>16384)throw new RangeError('Scroll source edge budget exceeded');
    const u=q.x*ux+q.y*uy,v=-q.x*uy+q.y*ux;
    if(!Number.isFinite(u)||!Number.isFinite(v))throw new RangeError('Source rotation overflow');
    if(!r.length||u!==r.at(-1).u||v!==r.at(-1).v)r.push({u,v});
  }if(r.length>1&&r[0].u===r.at(-1).u&&r[0].v===r.at(-1).v)r.pop();if(r.length>=3&&area(r)!==0)rings.push(r);}
  // Simple non-touching nested rings: winding belongs to the filled material,
  // not the input font convention. Self-intersecting rings are not supported.
  for(const r of rings){const depth=rings.filter(q=>q!==r&&contains(q,r[0].u,r[0].v)).length;if((area(r)>0)!==(depth%2===0))r.reverse();for(const p of r){minV=Math.min(minV,p.v);maxV=Math.max(maxV,p.v);}}
  const span=rings.length?maxV-minV:1,center=rings.length?(minV+maxV)/2:0;
  if(!Number.isFinite(span)||span<=0)throw new RangeError('Invalid source extent');
  const levels=[...new Set([...rings.flatMap(r=>r.map(p=>p.v)),...Array.from({length:rings.length?steps+1:0},(_,i)=>minV+span*i/steps)])].sort((a,b)=>a-b);
  const points=[],front=[],walls=[],wallNormals=[],lookup=new Map(),edges=[];let work=0;
  const tick=()=>{if(++work>maxWork)throw new RangeError('Scroll preparation work budget exceeded');};
  const node=(u,v)=>{const key=u+','+v;let id=lookup.get(key);if(id===undefined){id=points.length/2;if(id>=maxPoints)throw new RangeError('Scroll point budget exceeded');lookup.set(key,id);points.push(u,v);}return id;};
  const triangle=(a,b,c)=>{if((points[b*2]-points[a*2])*(points[c*2+1]-points[a*2+1])===(points[c*2]-points[a*2])*(points[b*2+1]-points[a*2+1]))return;front.push(a,b,c);if(front.length/3*2+walls.length*1>maxTriangles)throw new RangeError('Scroll triangle budget exceeded');};
  for(const r of rings){
    const shading=shadingTangents(r.map(p=>({x:p.u,y:p.v})),span*rimSmoothing);
    for(let i=0;i<r.length;i++){
      const a=r[i],b=r[(i+1)%r.length],du=b.u-a.u,dv=b.v-a.v,length=Math.hypot(du,dv),normal=[dv/length,-du/length];
      // Never use a filtered normal across the opposite side of this edge.
      const safe=n=>n&&n[0]*dv-n[1]*du>0?n:normal;
      edges.push({a,b,n0:safe(shading[i]),n1:safe(shading[(i+1)%r.length]),low:Math.min(a.v,b.v),high:Math.max(a.v,b.v)});
    }
  }
  const sorted=edges.filter(e=>e.low!==e.high).sort((a,b)=>a.low-b.low),active=new Set();let cursor=0;
  for(let j=0;j+1<levels.length;j++){
    const v0=levels[j],v1=levels[j+1];while(cursor<sorted.length&&sorted[cursor].low<=v0)active.add(sorted[cursor++]);
    const hits=[];for(const e of active){tick();if(e.high<v1){active.delete(e);continue;}hits.push(e);}
    hits.sort((a,b)=>(edgeAt(a,v0)/2+edgeAt(a,v1)/2)-(edgeAt(b,v0)/2+edgeAt(b,v1)/2));
    if(hits.length%2)throw new Error('Odd scroll crossing count');
    for(let i=0;i<hits.length;i+=2){const l=hits[i],r=hits[i+1],q=[node(edgeAt(l,v0),v0),node(edgeAt(r,v0),v0),node(edgeAt(r,v1),v1),node(edgeAt(l,v1),v1)];triangle(q[0],q[1],q[2]);triangle(q[0],q[2],q[3]);}
  }
  function lower(v){let a=0,b=levels.length;while(a<b){const m=(a+b)>>1;if(levels[m]<v)a=m+1;else b=m;}return a;}
  function wall(e,a,b){
    walls.push(a,b);
    for(const id of [a,b]){
      const du=e.b.u-e.a.u,dv=e.b.v-e.a.v;
      const t=clamp(Math.abs(du)>Math.abs(dv)?(points[id*2]-e.a.u)/du:(points[id*2+1]-e.a.v)/dv,0,1);
      wallNormals.push(e.n0[0]*(1-t)+e.n1[0]*t,e.n0[1]*(1-t)+e.n1[1]*t);
    }
  }
  for(const e of edges){
    if(e.low===e.high){wall(e,node(e.a.u,e.a.v),node(e.b.u,e.b.v));continue;}
    const lo=lower(e.low),hi=lower(e.high),forward=e.a.v<e.b.v;
    for(let j=lo;j<hi;j++){tick();const a=node(edgeAt(e,levels[j]),levels[j]),b=node(edgeAt(e,levels[j+1]),levels[j+1]);wall(e,...(forward?[a,b]:[b,a]));}
  }
  if(front.length/3*2+walls.length>maxTriangles)throw new RangeError('Scroll triangle budget exceeded');
  return {kind:'scroll-source-v1',axis,ux,uy,span,center,rings,levels:Float64Array.from(levels),points:Float64Array.from(points),front:Uint32Array.from(front),walls:Uint32Array.from(walls),wallNormals:Float64Array.from(wallNormals),rimSmoothing,stats:{inputPoints,points:points.length/2,frontTriangles:front.length/3,wallSegments:walls.length/2,work},maxTriangles};
}
function buildScrollSurface(source,input={},phase=0){
  if(source?.kind!=='scroll-source-v1'||!Number.isFinite(phase))throw new TypeError('Invalid scroll source or phase');
  const p=scrollSettings(input),h=p.gauge*source.span/2,sections=new Map();
  const sect=v=>{let s=sections.get(v);if(!s){s=scrollSection(v-source.center,source.span,p,phase);sections.set(v,s);}return s;};
  const positions=[],normals=[],faceNormals=[],sourceAxis=[],bounds={min:[Infinity,Infinity,Infinity],max:[-Infinity,-Infinity,-Infinity]};
  const vertex=(id,side)=>{const u=source.points[id*2],v=source.points[id*2+1],s=sect(v),sn=Math.sin(s.theta),cs=Math.cos(s.theta),off=side*h;
    const y=s.y+source.center-off*sn,z=s.z+off*cs;
    return {p:[source.ux*u-source.uy*y,source.uy*u+source.ux*y,z],n:[source.uy*sn*side,-source.ux*sn*side,cs*side],s};};
  const triangle=(a,b,c,axis)=>{const face=cross(sub(b.p,a.p),sub(c.p,a.p));if(!face.some(v=>v))return;
    if(![...a.p,...b.p,...c.p,...a.n,...b.n,...c.n,...face].every(Number.isFinite))throw new RangeError('Scroll geometry overflow');
    if(sourceAxis.length>=source.maxTriangles)throw new RangeError('Scroll triangle budget exceeded');
    // Visibility/winding must not depend on the filtered lighting field.
    if(dot(face,(a.g||a.n).map((v,i)=>v+(b.g||b.n)[i]+(c.g||c.n)[i]))<0)[b,c]=[c,b];
    const normal=unit(cross(sub(b.p,a.p),sub(c.p,a.p)));
    for(const q of [a,b,c]){positions.push(...q.p);normals.push(...q.n);for(let k=0;k<3;k++){bounds.min[k]=Math.min(bounds.min[k],q.p[k]);bounds.max[k]=Math.max(bounds.max[k],q.p[k]);}}
    faceNormals.push(...normal);sourceAxis.push(axis);
  };
  const front=Array.from({length:source.points.length/2},(_,i)=>vertex(i,1)),back=Array.from({length:source.points.length/2},(_,i)=>vertex(i,-1));
  for(let i=0;i<source.front.length;i+=3){const [a,b,c]=source.front.slice(i,i+3);triangle(front[a],front[b],front[c],0);triangle(back[c],back[b],back[a],1);}
  if(h)for(let i=0;i<source.walls.length;i+=2){const a=source.walls[i],b=source.walls[i+1],du=source.points[b*2]-source.points[a*2],dv=source.points[b*2+1]-source.points[a*2+1];
    const side=(id,sign,end)=>{const q=sign>0?front[id]:back[id],s=q.s,d=1-sign*h*s.curvature,cs=Math.cos(s.theta),sn=Math.sin(s.theta);
      const rotate=(x,y,z)=>unit([source.ux*x-source.uy*y,source.uy*x+source.ux*y,z]);
      const g=rotate(dv*d,-du*cs,-du*sn);
      if(!source.rimSmoothing||!source.wallNormals)return {p:q.p,n:g};
      // Cofactor of the sheet deformation: equivalent to inverse-transpose
      // normal transport up to a positive scalar. Do not rotate normals only.
      const k=i*2+end*2,nu=source.wallNormals[k],nv=source.wallNormals[k+1];
      return {p:q.p,n:rotate(nu*d,nv*cs,nv*sn),g};};
    const q=[side(a,-1,0),side(b,-1,1),side(b,1,1),side(a,1,0)];triangle(q[0],q[1],q[2],2);triangle(q[0],q[2],q[3],2);
  }
  return {positions:Float64Array.from(positions),normals:Float64Array.from(normals),faceNormals:Float64Array.from(faceNormals),sourceAxis:Uint8Array.from(sourceAxis),triangleCount:sourceAxis.length,bounds,stats:{sections:sections.size,triangles:sourceAxis.length},settings:p};
}
function renderScrollSurface(mesh,input={},frame={}){
  const p=scrollSettings(input);
  const ink=input.ink??[.56,.48,.37],back=input.backInk??ink,edge=input.edgeInk??ink;
  return renderAnamorphicSurface(mesh,{...p,finish:input.finish,ink,axisInks:[ink,back,edge],motion:0,depth:1},frame);
}

return {SCROLL_PRESETS,scrollSettings,scrollSection,prepareScrollSource,buildScrollSurface,renderScrollSurface};
})();
return {scroll: modules['scroll-type/core.mjs'], anamorphic: modules['anamorphic-type/core.mjs'], surface: modules['anamorphic-type/surface.mjs']};
}
root.TypeDeformerSculpture = {createEngine};
})(typeof globalThis !== 'undefined' ? globalThis : this);
