import {test,expect} from '@playwright/test';
import fs from 'node:fs';
const heavy={app:'type-deformer',version:92,text:'再開できる AA',params:{fontSize:5000,tensorSpacing:.1,textObjects:'[]'},letters:[{t:1,i:1,o:{tensorFiligree:{t:1,i:1}}}],composition:{enabled:true,type:'feedbackChamber'}};
async function open(page){const errors=[];page.on('pageerror',e=>errors.push(e.message));await page.route(/fonts\.googleapis\.com/,r=>r.fulfill({status:200,contentType:'text/css',body:''}));await page.addInitScript(data=>{if(!localStorage.getItem('seeded')){localStorage.setItem('typeDeformer.autosave.v1',JSON.stringify(data));localStorage.setItem('seeded','1');}},heavy);await page.goto('/');await page.waitForFunction(()=>document.querySelector('#autosaveStatus')?.textContent.includes('文字だけ'));return errors;}
async function save(page,id='btnSaveProj'){const event=new Promise(resolve=>{const finish=(kind,value)=>{page.off('download',d);page.off('popup',p);resolve({kind,value});},d=v=>finish('download',v),p=v=>finish('popup',v);page.once('download',d);page.once('popup',p);});const [{kind,value}]=await Promise.all([event,page.locator('#'+id).evaluate(e=>e.click())]);if(kind==='popup'){await value.waitForLoadState('domcontentloaded');const data=await value.evaluate(()=>JSON.parse(document.body.textContent));await value.close();return data;}return JSON.parse(fs.readFileSync(await value.path(),'utf8'));}
test('heavy stored project boots as plain text and its untouched original can be downloaded',async({page})=>{
 const errors=await open(page),data=await save(page);expect(data.text).toBe(heavy.text);expect(data.params.fontSize).toBeLessThan(1000);expect(data.composition.enabled).toBe(false);expect(data.letters.every(s=>!s.t&&!s.o)).toBe(true);expect(await page.evaluate(()=>TypeDeformerRenderJobs.inspect().every(q=>!q.busy&&q.counters.submitted===0))).toBe(true);
 expect(await save(page,'btnPreviousProject')).toEqual(heavy);await page.reload();await page.waitForFunction(()=>document.querySelector('#stageWorld')?.children.length>0);expect((await save(page)).letters.every(s=>!s.t&&!s.o)).toBe(true);expect(await save(page,'btnPreviousProject')).toEqual(heavy);expect(errors).toEqual([]);
});
test('refresh warns after editing, then clears effects even when a Share hash is present',async({page,browserName})=>{
 const errors=await open(page);if(browserName==='webkit')await page.locator('[data-mobile-section="text"]').click();await page.locator('#textInput').click();
 const data=await save(page);data.text='AA';data.params.fontSize=90;data.params.fontFamily='serif';data.letters=[0,1].map(()=>({t:0,l:0,i:0,o:{tensorFiligree:{t:1,i:1}}}));await page.locator('#projFile').setInputFiles({name:'effects.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(data))});await page.waitForFunction(()=>!document.querySelector('#surfaceFxCanvas').hidden);await page.evaluate(()=>{document.dispatchEvent(new Event('visibilitychange'));history.replaceState(null,'','#p=restart-should-not-render');});
 let warned=0;page.on('dialog',async d=>{if(d.type()==='beforeunload')warned++;await d.accept();});await page.reload();await page.waitForFunction(()=>document.querySelector('#stageWorld')?.children.length>0);const after=await save(page);expect(after.letters.every(s=>!s.t&&!s.o)).toBe(true);expect(after.composition.enabled).toBe(false);expect(new URL(page.url()).hash).toBe('');if(browserName!=='webkit')expect(warned).toBe(1);expect(errors).toEqual([]);
});
test('stuck real edit worker stops at its deadline and manual pause/resume leaves settings intact',async({page})=>{
 await open(page);const result=await page.evaluate(async()=>{const url=URL.createObjectURL(new Blob(['onmessage=()=>{while(true){}}'],{type:'text/javascript'}));let done;const stopped=new Promise(r=>done=r),q=TypeDeformerRenderJobs.create({editTimeout:150,workerFactory:()=>new Worker(url),onTimeout:done});q.request('heavy',{purpose:'edit'});await stopped;const state=q.status();q.dispose();URL.revokeObjectURL(url);return state;});expect(result.busy).toBe(false);expect(result.error).toContain('時間上限');
 const before=await save(page);await page.locator('#btnPauseRendering').click();await expect(page.locator('#btnPauseRendering')).toHaveText('描画を再開');expect(await save(page)).toEqual(before);await page.locator('#btnPauseRendering').click();await expect(page.locator('#btnPauseRendering')).toHaveText('描画を停止');
});
